# Generated by Django 4.2 on 2026-06-10 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='comapany',
            new_name='company',
        ),
    ]
